# 这些是支持此项目的推荐方式
github: [your_username]  # 替换为你的GitHub用户名
patreon: # 你的Patreon用户名
open_collective: # 你的Open Collective用户名
ko_fi: # 你的Ko-fi用户名
tidelift: # 你的Tidelift平台名称（例如：npm/babel）
community_bridge: # 你的Community Bridge项目名称
liberapay: # 你的Liberapay用户名
issuehunt: # 你的IssueHunt用户名
otechie: # 你的Otechie用户名
custom: ['https://paypal.me/yourusername'] # 自定义链接